services:
  db:
    image: postgres:alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kids
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./server.sql:/docker-entrypoint-initdb.d/server.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../app:/app
      - ../static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network: